module.exports = [
    {
name: 'Master Sword',
x: 500,
y: 300,
currentMapId: '12-10',
collectable: false,
respawn: 5,
itemType: 'Weapon',
maxStack: 1,
quantity: 0,
img: 'mastersword.png',
itemLevel: 10,
minDamage: 10,
maxDamage: 20,
flavorText: 'A sword of legends',
},
{
name: 'Master Blur',
x: 450,
y: 280,
currentMapId: '10-10',
collectable: false,
respawn: 5,
itemType: 'Weapon',
maxStack: 1,
quantity: 0,
img: 'link.png',
itemLevel: 10,
minDamage: 10,
maxDamage: 20,
flavorText: 'A sword of legends',
},
{
name: 'Master Durr',
x: 100,
y: 300,
currentMapId: '10-10',
collectable: false,
respawn: 5,
itemType: 'Weapon',
maxStack: 1,
quantity: 0,
img: 'armor.png',
itemLevel: 10,
minDamage: 10,
maxDamage: 20,
flavorText: 'A sword of legends',
},
];
